FROM node:20.12.0-alpine3.19

WORKDIR /usr/src/app

COPY package.json yarn.lock turbo.json tsconfig.json ./

COPY apps/user-app ./apps/user-app
COPY packages ./packages

RUN yarn install
RUN yarn db:generate

RUN yarn build

CMD ["yarn", "start-user-app"]